#!/usr/bin/env bash

set -e

PYENV_COMMAND="$1"
PYENV_COMMAND_PATH="$(pyenv-which "$PYENV_COMMAND")"
PYENV_BIN_PATH="${PYENV_COMMAND_PATH%/*}"

shopt -s nullglob
for script in "$(dirname "${BASH_SOURCE[0]}")/../../etc/pyenv.d/exec/"*.bash; do
  source "${script}"
done
shopt -u nullglob

shift 1
echo PYENV_BIN_PATH="${PYENV_BIN_PATH}" exec -a "${PYENV_COMMAND}" "$PYENV_COMMAND_PATH" "$@"
exec -a "${PYENV_COMMAND}" "$PYENV_COMMAND_PATH" "$@"
